name: Profeys
favicon: null
layout_spectrum: 0.06541651417501271
typography_spectrum: 0.5862712461967021
title: 'Profeysounet, Tino Turner, DoubleIchiouBoy, Blacksheep,Prof, Profeysito, Jolies Bouclettes'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2485579012427479
  lightness: 0.5252696117386222
  saturation: 0.6604202366434038
  rhythmicContrast: 0.43867462291382253
purpose: []
