name: Profeys
favicon: null
layout_spectrum: 0.07769
typography_spectrum: 0.5862712461967021
title: Bienvenue sur la page du Boy Prof
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff4900'
    - '#959597'
    - '#912b02'
  brandStrength: 0.1875
  lightness: 0.5252696117386222
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
