layout_spectrum: 0.4239797708578408
typography_spectrum: 0.29463420854881406
color:
  brandColors:
    - '#2DE9DB'
    - '#BBF7EF'
    - '#2B2122'
    - '#31AFA4'
    - '#A4967C'
  brandStrength: 0.33084321417845786
  lightness: 0.1454534693621099
  saturation: 0.49642187682911754
  rhythmicContrast: 0.3877571865450591
name: Profeys
favicon: null
title: Bienvenue sur la page du Boy Prof
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
